# Generated by Django 3.0 on 2021-04-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usrrg',
            old_name='mobile',
            new_name='age',
        ),
    ]
