# Generated by Django 3.0 on 2021-04-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0002_auto_20210403_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrrg',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
